import { DashboardLayout } from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useState } from "react";
import { AlertTriangle, ShieldCheck, Save, ArrowRight, ArrowLeft, Loader2, Check } from "lucide-react";
import { useStore } from "@/lib/store";
import { useUserData } from "@/hooks/use-user-data";
import { api } from "@/lib/api";
import { useToast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";

export default function DecisionEngine() {
  useUserData();
  
  const [stage, setStage] = useState(0);
  const [isProcessing, setIsProcessing] = useState(false);
  const { addDecision, setStats } = useStore();
  const { toast } = useToast();
  
  const [formData, setFormData] = useState({
    title: "",
    timeHorizon: "90 DAYS",
    context: "",
    options: ["", ""],
    worstCase: "",
    mitigation: "" // Generated by AI
  });

  const handleNext = () => setStage(prev => prev + 1);
  const handleBack = () => setStage(prev => prev - 1);

  const updateOption = (index: number, value: string) => {
    const newOptions = [...formData.options];
    newOptions[index] = value;
    setFormData({ ...formData, options: newOptions });
  };

  const addOption = () => {
    setFormData({ ...formData, options: [...formData.options, ""] });
  };

  const runSimulation = async () => {
    setIsProcessing(true);
    
    try {
      // Call AI synthesis API
      const { mitigation } = await api.synthesizeDecision({
        title: formData.title,
        timeHorizon: formData.timeHorizon,
        context: formData.context,
        options: formData.options.filter(o => o.trim()),
        worstCase: formData.worstCase
      });
      
      setFormData({ ...formData, mitigation });
      
      // Save to API
      const newDecision = await api.createDecision({
        date: new Date().toISOString().split('T')[0],
        title: formData.title,
        timeHorizon: formData.timeHorizon,
        context: formData.context,
        options: formData.options,
        worstCase: formData.worstCase,
        mitigation: mitigation,
        status: 'reviewed'
      });
      
      // Update local store
      addDecision(newDecision);
      
      // Update stats
      const updatedStats = await api.getStats();
      setStats({
        streak: updatedStats.streak,
        decisionsTracked: updatedStats.decisionsTracked,
        contentPieces: updatedStats.contentPieces
      });
      
      setIsProcessing(false);
      setStage(4);
      
      toast({
        title: "DECISION LOGGED",
        description: "Strategy saved to system memory.",
      });
    } catch (error) {
      console.error('Failed to save decision:', error);
      setIsProcessing(false);
      toast({
        title: "ERROR",
        description: "Failed to save decision. Please try again.",
        variant: "destructive"
      });
    }
  };

  return (
    <DashboardLayout>
       <header className="mb-8 flex justify-between items-end">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">DECISION_ENGINE</h1>
          <p className="text-muted-foreground font-mono text-sm">PRE_MORTEM_ANALYSIS_TOOL</p>
        </div>
        <div className="font-mono text-xs text-muted-foreground">
          STAGE {stage + 1}/5
        </div>
      </header>

      <div className="max-w-3xl mx-auto space-y-6">
        {/* Progress Bar */}
        <div className="w-full bg-secondary h-1 mb-8">
          <div 
            className="bg-primary h-full transition-all duration-500 ease-out" 
            style={{ width: `${((stage + 1) / 5) * 100}%` }}
          />
        </div>

        {stage === 0 && (
          <div className="space-y-6 animate-in slide-in-from-right-4 fade-in">
            <Card className="border-border bg-card">
              <CardHeader>
                <CardTitle className="font-mono text-sm uppercase tracking-wider text-muted-foreground flex items-center gap-2">
                  <AlertTriangle className="w-4 h-4" /> 01. Context Definition
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="space-y-2">
                  <label className="text-sm font-bold">Decision Title</label>
                  <Input 
                    placeholder="e.g. Pivot to Enterprise Sales" 
                    className="font-mono text-lg" 
                    value={formData.title}
                    onChange={(e) => setFormData({...formData, title: e.target.value})}
                    autoFocus
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-bold">Why now? What's the forcing function?</label>
                  <Textarea 
                    placeholder="e.g. Churn is increasing in SMB segment..." 
                    value={formData.context}
                    onChange={(e) => setFormData({...formData, context: e.target.value})}
                    className="min-h-[100px]"
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-bold">Time Horizon</label>
                  <div className="flex gap-2">
                    {["30 DAYS", "90 DAYS", "1 YEAR"].map((t) => (
                      <Button 
                        key={t}
                        variant={formData.timeHorizon === t ? "default" : "outline"} 
                        size="sm" 
                        onClick={() => setFormData({...formData, timeHorizon: t})}
                        className="font-mono text-xs"
                      >
                        {t}
                      </Button>
                    ))}
                  </div>
                </div>
              </CardContent>
            </Card>
            <div className="flex justify-end">
              <Button onClick={handleNext} disabled={!formData.title}>
                NEXT: OPTIONS <ArrowRight className="ml-2 w-4 h-4" />
              </Button>
            </div>
          </div>
        )}

        {stage === 1 && (
          <div className="space-y-6 animate-in slide-in-from-right-4 fade-in">
            <Card className="border-border bg-card">
               <CardHeader>
                <CardTitle className="font-mono text-sm uppercase tracking-wider text-muted-foreground">
                  02. Define Options
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <p className="text-sm text-muted-foreground">List at least 2 distinct paths forward.</p>
                {formData.options.map((opt, idx) => (
                  <div key={idx} className="flex gap-2">
                    <span className="font-mono text-sm pt-3 opacity-50">Option {String.fromCharCode(65 + idx)}</span>
                    <Input 
                      value={opt}
                      onChange={(e) => updateOption(idx, e.target.value)}
                      placeholder={`Path ${idx + 1}...`}
                      autoFocus={idx === 0}
                    />
                  </div>
                ))}
                <Button variant="ghost" size="sm" onClick={addOption} className="text-xs font-mono text-muted-foreground">
                  + ADD_OPTION
                </Button>
              </CardContent>
            </Card>
            <div className="flex justify-between">
              <Button variant="ghost" onClick={handleBack}>
                <ArrowLeft className="mr-2 w-4 h-4" /> BACK
              </Button>
              <Button onClick={handleNext} disabled={formData.options.some(o => !o)}>
                NEXT: PRE-MORTEM <ArrowRight className="ml-2 w-4 h-4" />
              </Button>
            </div>
          </div>
        )}

        {stage === 2 && (
          <div className="space-y-6 animate-in slide-in-from-right-4 fade-in">
             <Card className="border-destructive/30 bg-destructive/5">
               <CardHeader>
                <CardTitle className="font-mono text-sm uppercase tracking-wider text-destructive flex items-center gap-2">
                  <AlertTriangle className="w-4 h-4" /> 03. The Pre-Mortem
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <label className="text-sm font-bold text-destructive-foreground">Fast forward {formData.timeHorizon}. The decision FAILED catastrophically. Why?</label>
                  <p className="text-xs text-muted-foreground">Be brutal. Did you run out of cash? Did the team quit? Did competitors clone it?</p>
                  <Textarea 
                    value={formData.worstCase}
                    onChange={(e) => setFormData({...formData, worstCase: e.target.value})}
                    placeholder="It failed because..."
                    className="min-h-[150px] border-destructive/20 focus:border-destructive"
                    autoFocus
                  />
                </div>
              </CardContent>
            </Card>
            <div className="flex justify-between">
              <Button variant="ghost" onClick={handleBack}>
                <ArrowLeft className="mr-2 w-4 h-4" /> BACK
              </Button>
              <Button onClick={() => {
                setStage(3);
                runSimulation();
              }} disabled={!formData.worstCase} className="bg-destructive hover:bg-destructive/90 text-destructive-foreground">
                <ShieldCheck className="mr-2 w-4 h-4" /> RUN_SIMULATION
              </Button>
            </div>
          </div>
        )}

        {stage === 3 && (
           <div className="h-[400px] flex flex-col items-center justify-center space-y-4 animate-in fade-in">
             <Loader2 className="w-12 h-12 animate-spin text-primary" />
             <div className="font-mono text-sm animate-pulse">ANALYZING FAILURE MODES...</div>
             <div className="text-xs text-muted-foreground">Generating mitigation strategy...</div>
           </div>
        )}

        {stage === 4 && (
          <div className="space-y-6 animate-in slide-in-from-bottom-8 fade-in duration-700">
             <Card className="border-primary/50 bg-primary/5 shadow-lg shadow-primary/5">
               <CardHeader>
                <CardTitle className="font-mono text-sm uppercase tracking-wider text-primary flex items-center gap-2">
                  <ShieldCheck className="w-4 h-4" /> 04. Strategic Output
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="prose dark:prose-invert prose-sm font-mono whitespace-pre-line">
                  {formData.mitigation}
                </div>
              </CardContent>
            </Card>

            <div className="flex justify-center gap-4 pt-4">
               <Button variant="outline" onClick={() => window.location.href = '/'} className="font-mono">
                 RETURN_TO_BASE
               </Button>
               <Button onClick={() => window.print()} className="font-mono">
                 <Save className="mr-2 w-4 h-4" /> SAVE_TO_ARCHIVE
               </Button>
            </div>
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
